### ISSUE TITLE
Bibl Search by Date Works but has a bug

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#106]
The date range works but seems to cut off by one year on each end, thus if you enter

http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/search.html?q=&title=&author=&subject-exact=&mss=&pub-place=&publisher=&start-date=1990&end-date=1991&idno=

You get no results because there is no date allowed.

**Comment by wsalesky** [comment]
Is this still a problem?

**Comment by davidamichelson** [comment]
hmm, still seems broken on the start end. So a search for publications 1990-1991 excludes 1990 from the result:
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/search.html?q=&title=&author=&pub-place=&publisher=&start-date=1990&end-date=1991&idno=

The expectation from the user would be that the results would include 1990 and 1991

**Comment by wsalesky** [comment]
Ah, sorry  I see. I will take a look. I think I know what went wrong.

**Comment by wsalesky** [comment]
@davidamichelson This should now be fixed. Please let me know if it is not working as expected.

**Comment by davidamichelson** [comment]
@wsalesky alas this issue is still present.

Here is an example:

This search: https://caesarea-maritima.org/bibl/search.html?q=Caesarea&title=&author=&pub-place=&publisher=&start-date=1960&end-date=1961&idno=&start=1&sort-element=pubDate

should return items with publication dates of 1960 and 1961

but it only returns items with dates from 1961

To get the 1960 results one has to set the search parameter to 1959 to 1961
https://caesarea-maritima.org/bibl/search.html?q=Caesarea&title=&author=&pub-place=&publisher=&start-date=1959&end-date=1961&idno=

The users will expect that start date to be included, so can you add a -1 to the way it constructs the search parameter please?

**Comment by wsalesky** [comment]
Okay, I think this is really fixed now. Please let me know.

**Comment by davidamichelson** [comment]
Yes! This is done!
