### ISSUE TITLE
Display issues on records lacking a translation

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#222]
There are a handful of records for which we lack a translation. This would apply to the following records:

https://caesarea-maritima.org/testimonia/1
https://caesarea-maritima.org/testimonia/53
https://caesarea-maritima.org/testimonia/54
https://caesarea-maritima.org/testimonia/55

I these records' lack of `/TEI/text/body/ab[@type="translation"]` (or perhaps it's the lack of `/TEI/text/body/ab/anchor`?) is causing several display issues.

- The "see more text" button does not work on these records (this would only apply to https://caesarea-maritima.org/testimonia/1 as it is sufficiently long enough)
- The "Browse Source Text" button does not appear on these records
- The records' bibls are repeated following the cited text (although they do appear properly in the "Bibliography" section)

@davidamichelson let me know if you notice anything else with these records, but I think that's it.

**Comment by wsalesky** [comment]
@wlpotter This should be fixed. Close if you agree.

**Comment by wlpotter** [comment]
@wsalesky I'm still getting the same display issues, even after reloading the page. See below a screenshot of https://caesarea-maritima.org/testimonia/1

![image](https://user-images.githubusercontent.com/44096602/104034190-2f926680-5196-11eb-83de-36ce862f7ef4.png)

**Comment by wsalesky** [comment]
Sorry, bad copy/paste error in the XSLT. Should be fixed.

**Comment by davidamichelson** [comment]
Yay!

**Comment by wlpotter** [comment]
Yes, that worked. Thanks!
